#!/usr/bin/env ruby
require 'rukov'

case ARGV[0]
when 'study'
  Rukov.study(ARGV[1])
when 'learn'
  Rukov.learn(ARGV[1])
when 'speak'
  puts Rukov.speak
when 'clear'
  Rukov.clear
else
  raise ArgumentError, 'Unknown command. [learn]'
end
