#!/usr/bin/env ruby
require 'rukov'

case ARGV[0]
when 'study'
  puts Rukov.study(ARGV[1])
when 'learn'
  puts Rukov.learn(ARGV[1])
when 'load'
  puts Rukov.load
when 'speak'
  puts Rukov.speak
else
  raise ArgumentError, 'Unknown command. [learn]'
end
